export const videoData = [
  {
    id: 1,
    data: [
      {
        text: "7 DẤU HIỆU CẢNH BÁO KHỚP CỦA BẠN ĐANG “XUỐNG CẤP” MÀ NHIỀU NGƯỜI BỎ QUA",
        code: "YTETV_201",
        textView: null,
        typingtext: "yes",
        typingSound: "yes",
        img: "YTETV_201.jpg",
        timePlus: 1,
        duration: null,
      },
      {
        text: "1. Cứng khớp buổi sáng",
        code: "YTETV_202",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_202.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Nếu sáng dậy bạn phải xoay vai, xoay lưng vài phút mới cử động trơn tru, đó là dấu hiệu khớp đã mất đi độ trơn láng của sụn.",
        code: "YTETV_203",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_202.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "2. Kêu lạo xạo khi cử động",
        code: "YTETV_204",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_204.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Âm thanh “rắc rắc” khi gập gối, cúi lưng là dấu hiệu sụn khớp đang mòn, hai đầu xương cọ sát nhau.",
        code: "YTETV_205",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_204.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "3. Đau khi thay đổi thời tiết",
        code: "YTETV_206",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_206.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Sự thay đổi áp suất làm dịch khớp phản ứng — đây là dấu hiệu khớp yếu, kém đàn hồi.",
        code: "YTETV_207",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_206.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "4. Sưng nhẹ vùng quanh khớp",
        code: "YTETV_208",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_208.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Khớp bị viêm mạn tính sẽ sưng nhẹ, nhất là sau khi vận động hoặc đứng lâu.",
        code: "YTETV_209",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_208.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "5. Mỏi khớp khi ngồi lâu",
        code: "YTETV_210",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_210.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Ngồi lâu, đứng lâu mà khớp mỏi nhanh là do giảm tưới máu nuôi sụn khớp.",
        code: "YTETV_211",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_210.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "6. Hạn chế tầm vận động",
        code: "YTETV_212",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_212.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Không thể duỗi hoặc gập hết cỡ — dấu hiệu cấu trúc khớp đã bị tổn thương.",
        code: "YTETV_213",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_212.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "7. Nghe tiếng “bóp” hoặc “nổ” trong khớp khi vận động mạnh",
        code: "YTETV_214",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_214.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Nếu đi kèm đau, đó không còn là “bình thường” mà là tổn thương cơ học.",
        code: "YTETV_215",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_214.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Lời khuyên bác sĩ: Nếu bạn có từ 2 dấu hiệu trở lên, nên kiểm tra khớp sớm — vì sụn khớp không tái sinh, chỉ có thể bảo tồn kịp thời.",
        code: "YTETV_216",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_216.png",
        timePlus: 0.2,
        duration: null,
      },
    ],
  },
  {
    id: 2,
    data: [
      {
        text: "5 THÓI QUEN TƯỞNG VÔ HẠI NHƯNG ÂM THẦM “PHÁ” KHỚP GỐI CỦA BẠN",
        code: "YTETV_301",
        textView: null,
        typingtext: "yes",
        typingSound: "yes",
        img: "YTETV_301.jpg",
        timePlus: 1,
        duration: null,
      },
      {
        text: "1. Ngồi xổm, ngồi gập gối lâu",
        code: "YTETV_302",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_302.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Áp lực lên khớp gối tăng gấp 3–4 lần trọng lượng cơ thể, làm sụn nhanh hỏng.",
        code: "YTETV_303",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_302.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "2. Leo cầu thang quá nhiều",
        code: "YTETV_304",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_304.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Mỗi bước leo là một “cú dồn lực” vào sụn chêm — nếu làm thường xuyên, dễ tổn thương khớp.",
        code: "YTETV_305",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_304.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "3. Mang giày cao gót",
        code: "YTETV_306",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_306.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Thay đổi góc khớp gối, dồn trọng tâm ra trước khiến khớp phải chịu lực lệch.",
        code: "YTETV_307",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_306.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "4. Thừa cân, béo bụng",
        code: "YTETV_308",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_308.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Mỗi 1 kg tăng thêm, khớp gối phải gánh thêm khoảng 4 kg áp lực khi đi lại.",
        code: "YTETV_309",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_308.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "5. Không tập cơ đùi và cơ mông",
        code: "YTETV_310",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_310.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Cơ quanh khớp yếu khiến khớp chịu toàn bộ tải trọng — dễ đau và viêm.",
        code: "YTETV_311",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_310.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Lời khuyên: Tập cơ đùi trước, đi bộ nhẹ hoặc đạp xe, hạn chế ngồi xổm – đó là “bảo hiểm” tốt nhất cho khớp gối.",
        code: "YTETV_312",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_216.png",
        timePlus: 0.2,
        duration: null,
      },
    ],
  },
  {
    id: 3,
    data: [
      {
        text: "3 BÀI TẬP ĐƠN GIẢN GIÚP GIẢM ĐAU LƯNG HIỆU QUẢ HƠN CẢ THUỐC",
        code: "YTETV_401",
        textView: null,
        typingtext: "yes",
        typingSound: "yes",
        img: "YTETV_401.jpg",
        timePlus: 1,
        duration: null,
      },
      {
        text: "1. Kéo giãn cơ lưng – gối ngực",
        code: "YTETV_402",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_402.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Nằm ngửa, kéo một gối về ngực, giữ 15 giây rồi đổi bên. Giúp giãn cột sống thắt lưng, giảm chèn ép thần kinh.",
        code: "YTETV_403",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_402.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "2. Tư thế “mèo - bò” (Cat-Cow)",
        code: "YTETV_404",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_404.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Chống tay và gối, uốn lưng lên – xuống nhẹ nhàng. Kích hoạt các nhóm cơ dọc sống lưng, tăng đàn hồi khớp cột sống.",
        code: "YTETV_405",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_404.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "3. Plank cơ bản (30 giây)",
        code: "YTETV_406",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_406.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Giữ cơ bụng, lưng, mông thẳng hàng. Tăng sức bền vùng core, giảm tải trọng cho cột sống thắt lưng.",
        code: "YTETV_407",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_406.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Lời khuyên: Tập 10 phút mỗi ngày, duy trì 3–4 tuần, hiệu quả hơn uống thuốc giảm đau ngắn hạn.",
        code: "YTETV_408",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_216.png",
        timePlus: 0.2,
        duration: null,
      },
    ],
  },
  {
    id: 4,
    data: [
      {
        text: "6 LÝ DO BẠN BỊ ĐAU VAI GÁY MÃI KHÔNG KHỎI DÙ ĐÃ XOA BÓP VÀ DÁN CAO",
        code: "YTETV_501",
        textView: null,
        typingtext: "yes",
        typingSound: "yes",
        img: "YTETV_501.jpg",
        timePlus: 1,
        duration: null,
      },
      {
        text: "1. Ngồi sai tư thế lâu",
        code: "YTETV_502",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_502.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Cúi đầu dùng điện thoại, làm việc trước máy tính quá lâu gây co cứng cơ cổ.",
        code: "YTETV_503",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_502.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "2. Thiếu vận động cổ, vai",
        code: "YTETV_504",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_504.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Không xoay duỗi cổ thường xuyên khiến cơ bị “đóng băng”.",
        code: "YTETV_505",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_504.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "3. Gối kê cao khi ngủ",
        code: "YTETV_506",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_506.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Gây gập cổ, làm hẹp lỗ thoát dây thần kinh cổ.",
        code: "YTETV_507",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_506.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "4. Làm việc căng thẳng, stress kéo dài",
        code: "YTETV_508",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_508.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Stress khiến cơ vùng cổ – vai tăng trương lực, gây đau mỏi.",
        code: "YTETV_509",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_508.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "5. Không điều trị gốc rễ (thoái hóa, thoát vị)",
        code: "YTETV_510",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_510.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Xoa bóp chỉ giảm cơ, không xử lý nguyên nhân thần kinh.",
        code: "YTETV_511",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_510.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "6. Lạm dụng cao dán, dầu nóng",
        code: "YTETV_512",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_512.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Gây kích ứng da, thậm chí bỏng nhẹ mà không giải quyết vấn đề thật.",
        code: "YTETV_513",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_512.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Lời khuyên: Hãy kiểm tra cột sống cổ nếu đau vai gáy kéo dài trên 2 tuần. Điều trị đúng tầng đốt sống, cơn đau sẽ dứt hẳn.",
        code: "YTETV_514",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_216.png",
        timePlus: 0.2,
        duration: null,
      },
    ],
  },
  {
    id: 5,
    data: [
      {
        text: "4 SAI LẦM KHI UỐNG THUỐC GIẢM ĐAU KHIẾN BỆNH KHỚP NẶNG HƠN",
        code: "YTETV_601",
        textView: null,
        typingtext: "yes",
        typingSound: "yes",
        img: "YTETV_601.jpg",
        timePlus: 1,
        duration: null,
      },
      {
        text: "1. Uống thuốc khi chưa xác định nguyên nhân",
        code: "YTETV_602",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_602.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Không phân biệt đau do viêm, thoái hóa hay chấn thương dẫn đến dễ chọn sai loại thuốc.",
        code: "YTETV_603",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_602.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "2. Uống liên tục không theo hướng dẫn bác sĩ",
        code: "YTETV_604",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_604.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Thuốc giảm đau kháng viêm có thể gây viêm loét dạ dày, tổn thương gan thận.",
        code: "YTETV_605",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_604.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "3. Kết hợp nhiều loại thuốc cùng lúc",
        code: "YTETV_606",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_606.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Một số hoạt chất trùng lặp, gây quá liều hoặc phản ứng phụ nguy hiểm.",
        code: "YTETV_607",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_606.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "4. Dừng thuốc đột ngột hoặc tự thay đổi liều",
        code: "YTETV_608",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_608.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Khi chưa xử lý gốc bệnh, cơn đau tái phát nhanh hơn và nặng hơn.",
        code: "YTETV_609",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_608.jpg",
        timePlus: 0.2,
        duration: null,
      },
      {
        text: "Lời khuyên: Thuốc chỉ là một phần trong điều trị. Quan trọng hơn là vận động đúng, kiểm soát cân nặng, và theo dõi chuyên khoa.",
        code: "YTETV_610",
        textView: null,
        typingtext: "yes",
        typingSound: "no",
        img: "YTETV_216.png",
        timePlus: 0.2,
        duration: null,
      },
    ],
  },
];
